import React from 'react'

const Trainers = () => {
    return (
        <div>
            <h1>Trainers Page</h1>
        </div>
    )
}


export const metadata = {
    title: "Trainer | Courses",
    description: "Generated by create next app",
  }

export default Trainers;
