import React from 'react'

const Categories = () => {
    return (
        <div>
            <h1>Categories Page</h1>
        </div>
    )
}


export const metadata = {
    title: "Categories",
    description: "Generated by create next app",
}

export default Categories;
